###################################################################################
###   Create the cluster using kubeadm
###################################################################################
- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=unix:///run/containerd/containerd.sock

- name: Wait for port 6443 to become open on the host, don't start checking for 10 seconds
  ansible.builtin.wait_for:
    port: 6443
    delay: 10

- name: Setup kubeconf for ubuntu
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/ubuntu/.kube
    - cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
    - chown ubuntu:ubuntu /home/ubuntu/.kube/
    - chown ubuntu:ubuntu /home/ubuntu/.kube/config

- name: Install flannel
  command: "{{ item }}"
  become: false # Do not use root to install fannnel
  with_items:
    - kubectl apply -f https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml --validate=false

- name: Get k8s join command
  ansible.builtin.command: kubeadm token create  --print-join-command
  register: kubernetes_join_command

- name: Print join command
  ansible.builtin.debug:
    msg: "{{ kubernetes_join_command.stdout }}"

- name: Copy join command to local ansible directory
  become: no
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="./kubernetes_join_command" mode=0777
