###################################################################################
###  Instructions can be found here:
###  https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
###################################################################################
- name: Install curl
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - curl

###################################################################################
###   Disable swap (Check swap with free -h command)
###################################################################################
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

###################################################################################
###   Install containerd
###################################################################################
- name: Install containerd
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - containerd

###################################################################################
###  Enable IPv4 packet forwarding
###################################################################################
- name: Setup IP forwarding
  command: "{{ item }}"
  become: yes
  with_items:
    - sysctl -w net.ipv4.ip_forward=1
    - modprobe br_netfilter
    - sh -c 'echo "br_netfilter" > /etc/modules-load.d/br_netfilter.conf'
    - systemctl restart systemd-modules-load.service

###################################################################################
###  Ensure SystemdCgroup is set to true
### (https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd-systemd)
###################################################################################
- name: Ensure containerd config directory exists.
  file:
    path: /etc/containerd
    state: directory
  register: containerd_dir

- name: Create default containerd config
  shell: "{{ item }}"
  become: yes
  with_items:
    - containerd config default > /etc/containerd/config.toml

- name: Ensure SystemdCgroup is set to true
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^(\s*SystemdCgroup\s*=\s*).*'
    line: '            SystemdCgroup = true'
    backrefs: yes


- name: Restart containerd
  command: "{{ item }}"
  become: yes
  with_items:
    - systemctl restart containerd

###################################################################################
###   Install kubelet, kubeadm and kubectl
###   (https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/#how-to-migrate-deb)
###################################################################################
- name: Get Kubernetes package key
  shell: "{{ item }}"
  with_items:
    - curl -fsSL {{ k8s_url_apt_key }} | gpg --dearmor -o {{ k8s_gpgpath }}
  args:
    creates: "{{ k8s_gpgpath }}"


- name: Install Kubernetes repository
  apt_repository:
    filename: kubernetes
    repo: "deb [signed-by={{ k8s_gpgpath }}] {{ k8s_repository }} /"

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
