---
# file: worker.yml
- hosts: worker
  become: True
  roles:
     - role: echo
       vars:
          user: ec2-user
          nvidia: "no"
          proxy: "no"
          kubernetes_version: 1.22.0-00
          keadm_version: 1.6.2
          keadm_host_os: linux-amd64
